version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - ODDS_API_KEY=
      - SPORT=soccer_epl
      - POLL_INTERVAL=5
    volumes:
      - ./backend:/app/backend
